### ISSUE TITLE
GitHub Actions Auto Update

### ISSUE THREAD

**Issue by M1kep** [VladRassokhin/terraform-metadata#12]
I'm interested in building out a GitHub actions workflow that would allow periodic automatic updates of the schemas. Before I put much time into it, I'd like to confirm if this is something of interest or if there's any problems that may arise?

So far the primary issue I've found with automatic updates will be when new providers are located the provider.base.json needs to be updated. But realistically I'd think that something can be done to create an issue automatically when this is detected.

**Comment by M1kep** [comment]
I gave up on this awhile back due to my lack of understanding, and the silence from the repo owner here. Somebody else has done a bit of work and has a repository with auto builds running now: https://github.com/cageyv/terraform-metadata

I'm going to start working on repairing the remaining providers again and will merge my changes into the linked repo above(Assuming they accept the PRs like they have been) now that there is a good place to run these builds. I'm not sure about the direction @cageyv is wanting to take their repository, but it's by far the best way to get updated schemas currently.

**Comment by cageyv** [comment]
I will try to support this process as much as possible.
Automatic builds set up on a weekly basis
in case of errors I will find out about it :)
