### ISSUE TITLE
Archived Providers

### ISSUE THREAD

**Issue by M1kep** [VladRassokhin/terraform-metadata#13]
How should Archived Providers that have been transferred be handled?

For example:

https://github.com/hashicorp/terraform-provider-avi has been archived and transferred to https://github.com/vmware/terraform-provider-avi

I'm looking to better understand how this should be handled in the providers.base.json? Should the new repository be put into the "avi" key, or should something like "avi-vmware" be created?

**Comment by VladRassokhin** [comment]
Yeah, fixed path to almost all of them recently.
